# your domain
domain: dizhizhuaqu.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files: 
  # use local file
  - ./config/source.yaml
  # use web file
  - https://skyi.herokuapp.com/source.yaml
