# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 7891

# (HTTP and SOCKS5 in one port)
# mixed-port: 7890

# redir port for Linux and macOS
# redir-port: 7892

allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

proxy-groups:
  - name: 全局选择
    type: select
    proxies:
      - 手动选择2
      - 失败切换
      - 手动选择1
      - 负载均衡
  - name: 手动选择1
    type: select
    use:
      - websubvmess
      - test

  - name: 手动选择2
    type: select
    proxies:
      - 分类测试vmess
      - 分类测试本地
      - 分类测试全部
      - 分类测试ss
      - 分类测试ssr

  - name: 负载均衡
    type: load-balance
    url: 'http://www.gstatic.com/generate_204'
    interval: 900
    proxies:
      - 分类测试vmess
      - 分类测试本地
      - 分类测试全部
      - 分类测试ss
      - 分类测试ssr


  - name: 失败切换
    type: fallback
    url: 'http://www.gstatic.com/generate_204'
    interval: 900
    proxies:
      - 分类测试本地
      - 分类测试vmess
      - 分类测试ss
      - 分类测试ssr



  - name: 分类测试全部
    type: url-test
    url: 'https://www.bilibili.com/'
    interval: 1200
    use:
      - websub
  - name: 分类测试本地
    type: url-test
    url: 'https://www.bilibili.com/'
    interval: 1200
    use:
      - test
  - name: 分类测试vmess
    type: url-test
    url: 'https://www.bilibili.com/'
    interval: 1200
    use:
      - websubvmess
  - name: 分类测试ssr
    type: url-test
    url: 'https://www.bilibili.com/'
    interval: 1200
    use:
      - websubssr
  - name: 分类测试ss
    type: url-test
    url: 'https://www.bilibili.com/'
    interval: 1200
    use:
      - websubss

proxy-providers:
  websub:
    type: http
    url: "https://{{ .domain }}/clash/proxies"
    interval: 86400
    path: ./websub.yaml
    health-check:
      enable: true
      interval: 900
      url: http://www.gstatic.com/generate_204

  websubss:
    type: http
    url: "https://{{ .domain }}/clash/proxies?type=ss"
    interval: 86400
    path: ./websubss.yaml
    health-check:
      enable: true
      interval: 900
      url: http://www.gstatic.com/generate_204

  websubssr:
    type: http
    url: "https://{{ .domain }}/clash/proxies?type=ssr"
    interval: 86400
    path: ./websubssr.yaml
    health-check:
      enable: true
      interval: 900
      url: http://www.gstatic.com/generate_204

  websubvmess:
    type: http
    url: "https://{{ .domain }}/clash/proxies?type=vmess"
    interval: 86400
    path: ./websubvmess.yaml
    health-check:
      enable: true
      interval: 900
      url: http://www.gstatic.com/generate_204

  test:
    type: file
    path: ./test.yaml
    health-check:
      enable: true
      interval: 900
      url: http://www.gstatic.com/generate_204
rules:
  - DOMAIN-SUFFIX,smtp,DIRECT
  - DOMAIN-KEYWORD,aria2,DIRECT

  - GEOIP,CN,DIRECT

  - MATCH,全局选择
